CREATE TABLE product(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(100),
    price INT,
    quantity SMALLINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (product_id)
);